### ISSUE TITLE
Unable to getMatchingRecord if record is related to multiple entities

### ISSUE THREAD

**Issue by gjunkie** [mysidewalk/jsonapi-parse#10]
Hi there, thanks for putting this together! From my initial tests this thing is _very_ fast. Loving it. I've been looking to integrate this with some of the work we're doing and ran into an issue. I'm hoping you can provide some advice.

The method `getMatchingRecord` has logic to determine if a relationship has been marked as a `parent` (already populated with data). If it has, rather than populating it's related fields again and returning that, it returns the relationship itself. I see why the logic is written this way. It prevents an infinite loop. Especially handy for potentially infinitely nested relationships. 

The issue that I've run into is, I've got multiple examples where a relationship could be related to multiple things. So the first time it goes through this, it returns the populated relationship, but subsequent times it returns the plain relationship. For example:

Say you have a `group` that can have any number of users. And say you can have many groups. Users may belong to more than one group. Now let's say you have a `user` and this user has a relationship (like an avatar, or whatever else).

If this user is a member of multiple groups, the first group gets the user populated (and at that time marked as a parent, since they have relationships). But when we run through the second group the method will return the relationship when it runs into the same user again. Looking for any advice you can give on how to handle a situation like this. Thank you!

**Comment by pjfreeze** [comment]
@gjunkie

Hmm, that sounds quite unexpected. You are absolutely right about the lgoic trying to prevent circular references.

Would you share a JSON example of what you described with the many-to-many relationship? I wasn't able to determine which model was the primary model and which was the included model.

**Comment by gjunkie** [comment]
Yeah no problem. My data looks something like this, I think it captures what I'm getting after. In this case the `user` with `id` of `456` won't be populated when populating group 2 because that user was marked as a parent due to its `avatar` relationship.

```
{
  data: {
    type: "locations",
    id: "1",
    relationships: {
      groups: {
        data: [
          { type: "groups", id: "1" },
          { type: "groups", id: "2" },
        ]
      }
    }
  },
  included: [
    {
      type: "groups",
      id: "1",
      name: "My First Group",
      relationships: {
        users: {
          data: [
            { type: "users", id: "456" },
            { type: "users", id: "789" }
          ]
        }
      }
    },
    {
      type: "groups",
      id: "2",
      name: "My Second Group",
      relationships: {
        users: {
          data: [
            { type: "users", id: "456" }
          ]
        }
      }
    },
    {
      type: "users",
      id: "456",
      first_name: "john",
      last_name: "appleseed",
      relationships: {
        avatar: {
          data: { type: "avatar", id: "123" }
        }
      }
    },
    {
      type: "users",
      id: "789",
      first_name: "marty",
      last_name: "mcfly",
      relationships: null
    },
    {
      type: "avatars",
      id: "123",
      image_url: "http://someurl.com/picture.jpg",
      relationships: {
        user: {
          data: { type: "users", id: "456" }
        }
      }
    }
  ]
}

**Comment by pjfreeze** [comment]
Hmmmmm...

I'm not getting the result you described in the original post.

This is what I converted your data to
``` json
{
  "data": {
    "type": "locations",
    "id": "1",
    "attributes": {},
    "relationships": {
      "groups": {
        "data": [
          {
            "type": "groups",
            "id": "1"
          },
          {
            "type": "groups",
            "id": "2"
          }
        ]
      }
    }
  },
  "included": [
    {
      "type": "groups",
      "id": "1",
      "attributes": {
        "name": "My First Group"
      },
      "relationships": {
        "users": {
          "data": [
            {
              "type": "users",
              "id": "456"
            },
            {
              "type": "users",
              "id": "789"
            }
          ]
        }
      }
    },
    {
      "type": "groups",
      "id": "2",
      "attributes": {
        "name": "My Second Group"
      },
      "relationships": {
        "users": {
          "data": [
            {
              "type": "users",
              "id": "456"
            }
          ]
        }
      }
    },
    {
      "type": "users",
      "id": "456",
      "attributes": {
        "first_name": "john",
        "last_name": "appleseed"
      },
      "relationships": {
        "avatar": {
          "data": {
            "type": "avatar",
            "id": "123"
          }
        }
      }
    },
    {
      "type": "users",
      "id": "789",
      "attributes": {
        "first_name": "marty",
        "last_name": "mcfly"
      },
      "relationships": null
    },
    {
      "type": "avatar",
      "id": "123",
      "attributes": {
        "image_url": "http://someurl.com/picture.jpg"
      },
      "relationships": {
        "user": {
          "data": {
            "type": "users",
            "id": "456"
          }
        }
      }
    }
  ]
}
```

### Output
``` json
```

**Comment by gjunkie** [comment]
Hmm. no I think that `type` was just a typo on my part here. Interesting. So from a high level, when this is parsing the second group and sees its user relations, which will trigger `getMatchingRecord` for those users, how is it _not_ just returning the relationship for you? Since `parents` gets passed around, theoretically that user would have been marked as a parent due to its avatar. My output looks more like this.

```
{
  "data": {
    "meta": {},
    "groups": [
      {
        "meta": {},
        "name": "My First Group",
        "users": [
          {
            "meta": {},
            "first_name": "john",
            "last_name": "appleseed",
            "avatar": {
              "meta": {},
              "image_url": "http://someurl.com/picture.jpg",
              "user": {
                "type": "users",
                "id": "456"
              },
              "id": "123",
              "type": "avatar"
            },
            "id": "456",
            "type": "users"
          },
          {
            "meta": {},
            "first_name": "marty",
            "last_name": "mcfly",
            "id": "789",
            "type": "users"
          }
        ],
        "id": "1",
        "type": "groups"
      },
      {
        "meta": {},
        "name": "My Second Group",
        "users": [
          {
            "id": "456",
            "type": "users"
          }
        ],
        "id": "2",
        "type": "groups"
      }
    ],
    "id": "1",
    "type": "locations"
  },
  "jsonapi": {
    "parsed": true
  }
}
```

**Comment by pjfreeze** [comment]
Haha okay, well glad you were able to get to the bottom of it. Unless there is something else related to the `getMatchingRecord` method that isn't working, I'll go ahead and close this.
