### ISSUE TITLE
Fetching included entity without attributes error

### ISSUE THREAD

**Issue by noahsiegrist** [mysidewalk/jsonapi-parse#11]
Our data model has a middle table without any exposed attributes. e.g. order_item -> reservation -> serial
I need the serial number, but loading the serial entity as included entity, results in an error. 

jsonapi.js (line 125)
Tries to add field on undefined:
`record.attributes[property] = getMatchingRecord` whereas attributes of record reservation is undefined. The only field ist the serial reference, which is not an attribute.

**Comment by pjfreeze** [comment]
Hey @noahsiegrist! Apologies for the delay on responding.

> I need the serial number, but loading the serial entity as included entity, results in an error.

I'm struggling to visualize this in my head. Could you include an example of the serialized data your server is sending? Also an example of how you expect it to be unpacked would be great!

**Comment by noahsiegrist** [comment]
I dont have the snipped anymore... But the issue was, that the entity did not have an `attributes` section. I'm not sure what the actual JSON:API definition is, maybe the issue is on the server implementation side...
But if the server did not send a `attributes` section on the record, because the record does not have any attributes. Only a relation.

**Comment by pjfreeze** [comment]
I'll take a look at that. From my understanding of the problem you are describing, the primary "resource" does not include any attributes. Doing a quick scan of the `v1.0` specification, it looks like attributes is NOT required.

I'll make sure the code works without expecting attributes for either primary resources or included resources.

Reference of required/optional attributes: https://jsonapi.org/format/#document-resource-objects

**Comment by pjfreeze** [comment]
Hey @noahsiegrist, I made a quick change that first checks for the presence of the `attributes` object before assigning to it. I updated the test to attempt to cover this case as well. Let me know if you have any addition issues after upgrading to `2.0.1`.

Thanks for reporting the issue!
